// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Synergy.Repository.Database;

namespace Synergy.Repository.Migrations
{
    [DbContext(typeof(SynergyDbContext))]
    [Migration("20200609205150_requestLog-ResponseLog")]
    partial class requestLogResponseLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Synergy.Repository.Models.ClientRequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnName("ClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateLogged")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DateLogged")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 6, 9, 20, 51, 50, 696, DateTimeKind.Utc).AddTicks(1038));

                    b.Property<string>("Payload")
                        .HasColumnName("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasColumnName("RequestMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestReferencId")
                        .HasColumnName("RequestrefernceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestUniqueRefernceId")
                        .IsRequired()
                        .HasColumnName("UniqueReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestLog");
                });

            modelBuilder.Entity("Synergy.Repository.Models.ClientResponseLog", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateLogged")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DateLogged")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 6, 9, 20, 51, 50, 704, DateTimeKind.Utc).AddTicks(3961));

                    b.Property<int>("HttpStatusCode")
                        .HasColumnName("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnName("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestUniqueRefernceId")
                        .IsRequired()
                        .HasColumnName("UniqueReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SynergyStatusCode")
                        .HasColumnName("SynergyStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResponseId");

                    b.ToTable("ResponseLog");
                });
#pragma warning restore 612, 618
        }
    }
}
